---
- name: Enable letsencrypt timer
  service: name=letsencrypt.timer state=started enabled=yes
- name: Generate certificate
  service: name=letsencrypt.service state=started
  when: not letsencrypt_noregen is defined
